const IMG = {
  water: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&auto=format&fit=crop&q=80',
  soda: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
  malt: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600&auto=format&fit=crop&q=80',
  redbull: 'https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=600&auto=format&fit=crop&q=80',
  beer: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&auto=format&fit=crop&q=80',
  wine: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80',
  macchiato: 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=600&auto=format&fit=crop&q=80',
  espresso: 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=600&auto=format&fit=crop&q=80',
  cappuccino: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&auto=format&fit=crop&q=80',
  latte: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&auto=format&fit=crop&q=80',
  coffee: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&auto=format&fit=crop&q=80',
  tea: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&auto=format&fit=crop&q=80',
  hotchoc: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=600&auto=format&fit=crop&q=80',
  juice: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&auto=format&fit=crop&q=80',
  shake: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=600&auto=format&fit=crop&q=80',
  smoothie: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed514?w=600&auto=format&fit=crop&q=80',
  breakfast: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80',
  omelette: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&auto=format&fit=crop&q=80',
  egg: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80',
  yogurt: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
  pancake: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
  salad: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
  pizza: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
  pasta: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&auto=format&fit=crop&q=80',
  rice: 'https://images.unsplash.com/photo-1536304993881-460e32f50647?w=600&auto=format&fit=crop&q=80',
  fish: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
  burger: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
  sandwich: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80',
  fries: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80',
  steak: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&auto=format&fit=crop&q=80',
  chicken: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&auto=format&fit=crop&q=80',
  cake: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
  tiramisu: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
  forest: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600&auto=format&fit=crop&q=80',
  banana: 'https://images.unsplash.com/photo-1601115074956-0eb78ab1b6b3?w=600&auto=format&fit=crop&q=80',
  sambusa: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=600&auto=format&fit=crop&q=80',
  bread: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
  cheese: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&auto=format&fit=crop&q=80',
  honey: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80',
  veg: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
  ethiopian: 'https://images.pexels.com/photos/36984977/pexels-photo-36984977/free-photo-of-delicious-traditional-ethiopian-meal-served-hot.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
};

export const FALLBACK_MENU = [
  // Beverages & Drinks
  { id: 1, name: '1/2 Liter Water', category: 'Beverages & Drinks', price: 60, description: '', image: IMG.water },
  { id: 2, name: '1/4 Liter Water', category: 'Beverages & Drinks', price: 43.47, description: '', image: IMG.water },
  { id: 3, name: '1 Liter Water', category: 'Beverages & Drinks', price: 69, description: '', image: IMG.water },
  { id: 4, name: 'Soft Drinks', category: 'Beverages & Drinks', price: 86.95, description: '', image: IMG.soda },
  { id: 5, name: 'Ambo', category: 'Beverages & Drinks', price: 86.95, description: '', image: IMG.soda },
  { id: 6, name: 'Malta Guinness', category: 'Beverages & Drinks', price: 180.40, description: '', image: IMG.malt },
  { id: 7, name: 'Soft Malt', category: 'Beverages & Drinks', price: 130.43, description: '', image: IMG.malt },
  { id: 8, name: 'Coke 500ml', category: 'Beverages & Drinks', price: 18.26, description: '', image: IMG.soda },
  { id: 9, name: 'Red Bull', category: 'Beverages & Drinks', price: 212.17, description: '', image: IMG.redbull },
  { id: 10, name: 'Rift Valley', category: 'Beverages & Drinks', price: 343.47, description: 'Wine', image: IMG.wine },
  { id: 11, name: 'Chardonnay', category: 'Beverages & Drinks', price: 255.65, description: 'Wine', image: IMG.wine },
  { id: 12, name: 'Accacia', category: 'Beverages & Drinks', price: 565.25, description: 'Wine', image: IMG.wine },
  { id: 13, name: 'Cavee', category: 'Beverages & Drinks', price: 382.60, description: 'Wine', image: IMG.wine },
  { id: 14, name: 'Axumit', category: 'Beverages & Drinks', price: 565, description: '', image: IMG.wine },
  { id: 15, name: 'Kemila', category: 'Beverages & Drinks', price: 782, description: '', image: IMG.wine },
  { id: 16, name: 'Beer', category: 'Beverages & Drinks', price: 130.04, description: '', image: IMG.beer },
  { id: 17, name: 'Gebeta', category: 'Beverages & Drinks', price: 382.60, description: 'Wine', image: IMG.wine },
  { id: 18, name: 'Novida', category: 'Beverages & Drinks', price: 78.21, description: '', image: IMG.soda },

  // Hot Drinks
  { id: 19, name: 'Macchiato', category: 'Hot Drinks', price: 130, description: '', image: IMG.macchiato },
  { id: 20, name: 'Fasting Macchiato', category: 'Hot Drinks', price: 173, description: '', image: IMG.macchiato },
  { id: 21, name: 'Coffee', category: 'Hot Drinks', price: 95.65, description: '', image: IMG.coffee },
  { id: 22, name: 'Traditional Coffee', category: 'Hot Drinks', price: 34.78, description: '', image: IMG.coffee },
  { id: 23, name: 'Espresso', category: 'Hot Drinks', price: 95.65, description: '', image: IMG.espresso },
  { id: 24, name: 'Milk with Coffee', category: 'Hot Drinks', price: 147, description: '', image: IMG.latte },
  { id: 25, name: 'American Coffee', category: 'Hot Drinks', price: 147, description: '', image: IMG.coffee },
  { id: 26, name: 'Cappuccino', category: 'Hot Drinks', price: 147.73, description: '', image: IMG.cappuccino },
  { id: 27, name: 'Café Latte', category: 'Hot Drinks', price: 147, description: '', image: IMG.latte },
  { id: 28, name: 'Special Tea', category: 'Hot Drinks', price: 252, description: '', image: IMG.tea },
  { id: 29, name: 'Tea', category: 'Hot Drinks', price: 52.17, description: '', image: IMG.tea },
  { id: 30, name: 'Lepton Tea', category: 'Hot Drinks', price: 34.78, description: '', image: IMG.tea },
  { id: 31, name: 'Tea Spice', category: 'Hot Drinks', price: 95.60, description: '', image: IMG.tea },
  { id: 32, name: 'Green Tea', category: 'Hot Drinks', price: 52.17, description: '', image: IMG.tea },
  { id: 33, name: 'Hot Milk', category: 'Hot Drinks', price: 147, description: '', image: IMG.latte },
  { id: 34, name: 'Ginger Tea', category: 'Hot Drinks', price: 69.56, description: '', image: IMG.tea },
  { id: 35, name: 'Peanut Tea', category: 'Hot Drinks', price: 95.65, description: '', image: IMG.tea },
  { id: 36, name: 'Tea with Lemon', category: 'Hot Drinks', price: 60.86, description: '', image: IMG.tea },
  { id: 37, name: 'Hot Chocolate', category: 'Hot Drinks', price: 156, description: '', image: IMG.hotchoc },

  // Juice & Shakes
  { id: 38, name: 'Dolphin Special Juice', category: 'Juice & Shakes', price: 347, description: '', image: IMG.juice },
  { id: 39, name: 'Banana Shake', category: 'Juice & Shakes', price: 173.90, description: '', image: IMG.shake },
  { id: 40, name: 'Mixed Juice', category: 'Juice & Shakes', price: 217, description: '', image: IMG.smoothie },
  { id: 41, name: 'Papaya', category: 'Juice & Shakes', price: 217, description: '', image: IMG.juice },
  { id: 42, name: 'Pineapple', category: 'Juice & Shakes', price: 217, description: '', image: IMG.juice },
  { id: 43, name: 'Avocado', category: 'Juice & Shakes', price: 304, description: '', image: IMG.smoothie },
  { id: 44, name: 'Strawberry', category: 'Juice & Shakes', price: 260, description: '', image: IMG.juice },
  { id: 45, name: 'Mango', category: 'Juice & Shakes', price: 304, description: '', image: IMG.juice },
  { id: 46, name: 'Strawberry with Milk', category: 'Juice & Shakes', price: 286, description: '', image: IMG.shake },
  { id: 47, name: 'Fruit Cocktail', category: 'Juice & Shakes', price: 173.04, description: '', image: IMG.smoothie },
  { id: 48, name: 'Strawberry Mix', category: 'Juice & Shakes', price: 260, description: '', image: IMG.juice },

  // Breakfast & Light Meals
  { id: 49, name: 'Dolphin Special Ful', category: 'Breakfast & Light Meals', price: 434, description: '', image: IMG.breakfast },
  { id: 50, name: 'Special Ful', category: 'Breakfast & Light Meals', price: 321.73, description: '', image: IMG.breakfast },
  { id: 51, name: 'Normal Ful', category: 'Breakfast & Light Meals', price: 304.34, description: '', image: IMG.breakfast },
  { id: 52, name: 'Yogurt', category: 'Breakfast & Light Meals', price: 130.14, description: '', image: IMG.yogurt },
  { id: 53, name: 'Tuna Sils', category: 'Breakfast & Light Meals', price: 365.21, description: '', image: IMG.fish },
  { id: 54, name: 'Egg with Tomato Sauce', category: 'Breakfast & Light Meals', price: 260.86, description: '', image: IMG.egg },
  { id: 55, name: 'Omelette with Cheese', category: 'Breakfast & Light Meals', price: 321.73, description: '', image: IMG.omelette },
  { id: 56, name: 'Fried Egg', category: 'Breakfast & Light Meals', price: 260.81, description: '', image: IMG.egg },
  { id: 57, name: 'Plain Omelette', category: 'Breakfast & Light Meals', price: 260.81, description: '', image: IMG.omelette },
  { id: 58, name: 'Tomato Sils', category: 'Breakfast & Light Meals', price: 243.45, description: '', image: IMG.breakfast },
  { id: 59, name: 'Scrambled Egg', category: 'Breakfast & Light Meals', price: 252.13, description: '', image: IMG.egg },
  { id: 60, name: 'Fetira with Honey', category: 'Breakfast & Light Meals', price: 260.86, description: '', image: IMG.pancake },
  { id: 61, name: 'Fetira with Egg', category: 'Breakfast & Light Meals', price: 286.95, description: '', image: IMG.pancake },
  { id: 62, name: 'Special Omelette', category: 'Breakfast & Light Meals', price: 330.43, description: '', image: IMG.omelette },
  { id: 63, name: 'Chechebsa', category: 'Breakfast & Light Meals', price: 260.25, description: '', image: IMG.pancake },
  { id: 64, name: 'Special Chechebsa', category: 'Breakfast & Light Meals', price: 313.04, description: '', image: IMG.pancake },
  { id: 65, name: 'Tef Chechebsa with Honey', category: 'Breakfast & Light Meals', price: 269.56, description: '', image: IMG.pancake },
  { id: 66, name: 'Tef Chechebsa with Egg', category: 'Breakfast & Light Meals', price: 304.34, description: '', image: IMG.pancake },
  { id: 67, name: 'Special Tef Chechebsa', category: 'Breakfast & Light Meals', price: 321.73, description: '', image: IMG.pancake },
  { id: 68, name: 'Tef Chechebsa Plain', category: 'Breakfast & Light Meals', price: 217.39, description: '', image: IMG.pancake },
  { id: 69, name: 'Special Fetira', category: 'Breakfast & Light Meals', price: 304.34, description: '', image: IMG.pancake },

  // Salad
  { id: 70, name: 'Dolphin Special Salad', category: 'Salad', price: 573, description: '', image: IMG.salad },
  { id: 71, name: 'Mixed Salad', category: 'Salad', price: 304.34, description: '', image: IMG.salad },
  { id: 72, name: 'Tuna Salad (Special)', category: 'Salad', price: 521.73, description: '', image: IMG.salad },
  { id: 73, name: 'Chicken Salad', category: 'Salad', price: 512.17, description: '', image: IMG.salad },

  // Pizza
  { id: 74, name: 'Dolphin Special Pizza 40x30cm', category: 'Pizza', price: 869, description: '', image: IMG.pizza },
  { id: 75, name: 'Special Pizza', category: 'Pizza', price: 739.13, description: '', image: IMG.pizza },
  { id: 76, name: 'Vegetable with Tuna', category: 'Pizza', price: 686.95, description: '', image: IMG.pizza },
  { id: 77, name: 'Margarita Pizza', category: 'Pizza', price: 608.69, description: '', image: IMG.pizza },
  { id: 78, name: 'Meat Lover Pizza', category: 'Pizza', price: 759, description: '', image: IMG.pizza },
  { id: 79, name: 'Chicken Pizza', category: 'Pizza', price: 730.43, description: '', image: IMG.pizza },
  { id: 80, name: 'Vegetable Pizza', category: 'Pizza', price: 521.73, description: '', image: IMG.pizza },
  { id: 81, name: 'Tuna Pizza', category: 'Pizza', price: 669.56, description: '', image: IMG.pizza },
  { id: 82, name: 'Altono Pizza', category: 'Pizza', price: 739.13, description: '', image: IMG.pizza },

  // Pasta & Rice
  { id: 83, name: 'Tomato Sauce Pasta', category: 'Pasta & Rice', price: 347, description: '', image: IMG.pasta },
  { id: 84, name: 'Bolognaise Sauce Pasta', category: 'Pasta & Rice', price: 391.30, description: '', image: IMG.pasta },
  { id: 85, name: 'Vegetable Pasta', category: 'Pasta & Rice', price: 347, description: '', image: IMG.pasta },
  { id: 86, name: 'Tuna Sauce Pasta', category: 'Pasta & Rice', price: 496.56, description: '', image: IMG.pasta },
  { id: 87, name: 'Vegetable with Tuna Pasta', category: 'Pasta & Rice', price: 478.26, description: '', image: IMG.pasta },
  { id: 88, name: 'Rice with Vegetable', category: 'Pasta & Rice', price: 347.82, description: '', image: IMG.rice },
  { id: 111, name: 'Lasagna', category: 'Pasta & Rice', price: 365.00, description: '', image: IMG.pasta },

  // Fish
  { id: 89, name: 'Fish Cutlet', category: 'Fish', price: 521.13, description: '', image: IMG.fish },
  { id: 90, name: 'Grilled Fish', category: 'Fish', price: 521.73, description: '', image: IMG.fish },
  { id: 91, name: 'Fish Goulash', category: 'Fish', price: 521.73, description: '', image: IMG.fish },
  { id: 92, name: 'Fish Package', category: 'Fish', price: 547.82, description: '', image: IMG.fish },
  { id: 93, name: 'Stir Fried Fish', category: 'Fish', price: 547.82, description: '', image: IMG.fish },

  // Burger & Sandwich
  { id: 94, name: 'Dolphin Special Double Beef Burger', category: 'Burger & Sandwich', price: 608.69, description: '', image: IMG.burger },
  { id: 95, name: 'Dolphin Special Burger', category: 'Burger & Sandwich', price: 565.21, description: '', image: IMG.burger },
  { id: 96, name: 'Beef Burger', category: 'Burger & Sandwich', price: 495.65, description: '', image: IMG.burger },
  { id: 97, name: 'Chicken Burger', category: 'Burger & Sandwich', price: 591.35, description: '', image: IMG.burger },
  { id: 98, name: 'Cheese Burger', category: 'Burger & Sandwich', price: 504.34, description: '', image: IMG.burger },
  { id: 99, name: 'Fish Burger', category: 'Burger & Sandwich', price: 460.80, description: '', image: IMG.burger },
  { id: 100, name: 'Tuna Sandwich', category: 'Burger & Sandwich', price: 478.26, description: '', image: IMG.sandwich },
  { id: 101, name: 'Club Sandwich', category: 'Burger & Sandwich', price: 521.43, description: '', image: IMG.sandwich },
  { id: 102, name: 'Vegetable Burger', category: 'Burger & Sandwich', price: 278.60, description: '', image: IMG.burger },
  { id: 103, name: 'Beef Combo', category: 'Burger & Sandwich', price: 478, description: '', image: IMG.burger },
  { id: 104, name: 'Egg Burger', category: 'Burger & Sandwich', price: 260.86, description: '', image: IMG.burger },
  { id: 105, name: 'French Fries', category: 'Burger & Sandwich', price: 304, description: '', image: IMG.fries },
  { id: 106, name: 'Chicken Combo', category: 'Burger & Sandwich', price: 539, description: '', image: IMG.chicken },
  { id: 107, name: 'Grilled Beef Fillet Steak', category: 'Burger & Sandwich', price: 469, description: '', image: IMG.steak },
  { id: 108, name: 'Roasted Chicken Breast', category: 'Burger & Sandwich', price: 565.21, description: '', image: IMG.chicken },
  { id: 109, name: 'Grilled Tilapia Fish', category: 'Burger & Sandwich', price: 460, description: '', image: IMG.fish },
  { id: 110, name: 'Chicken Sandwich', category: 'Burger & Sandwich', price: 539.00, description: '', image: IMG.sandwich },
  { id: 112, name: 'Tuna Club Sandwich', category: 'Burger & Sandwich', price: 608.69, description: '', image: IMG.sandwich },

  // Cake & Snacks
  { id: 113, name: 'Tiramisu with Cup', category: 'Cake & Snacks', price: 260.86, description: '', image: IMG.tiramisu },
  { id: 114, name: 'Tiramisu', category: 'Cake & Snacks', price: 260.86, description: '', image: IMG.tiramisu },
  { id: 115, name: 'Chocolate Cake', category: 'Cake & Snacks', price: 260.86, description: '', image: IMG.cake },
  { id: 116, name: 'White Forest Torta', category: 'Cake & Snacks', price: 1739.15, description: '', image: IMG.forest },
  { id: 117, name: 'Black Forest Torta', category: 'Cake & Snacks', price: 1739.13, description: '', image: IMG.forest },
  { id: 118, name: 'Tiramisu Torta', category: 'Cake & Snacks', price: 2173.91, description: '', image: IMG.tiramisu },
  { id: 119, name: 'Banana Cake', category: 'Cake & Snacks', price: 139.13, description: '', image: IMG.banana },
  { id: 120, name: 'Sambusa Meat', category: 'Cake & Snacks', price: 176, description: '', image: IMG.sambusa },
  { id: 121, name: 'Sambusa Lentil', category: 'Cake & Snacks', price: 156, description: '', image: IMG.sambusa },
  { id: 122, name: 'Black Forest', category: 'Cake & Snacks', price: 260.86, description: '', image: IMG.forest },
  { id: 123, name: 'White Forest', category: 'Cake & Snacks', price: 260.86, description: '', image: IMG.forest },
  { id: 124, name: 'Marble Cake', category: 'Cake & Snacks', price: 173, description: '', image: IMG.cake },
  { id: 125, name: 'Caramel Fasting', category: 'Cake & Snacks', price: 260.86, description: '', image: IMG.cake },

  // Extras
  { id: 126, name: 'Bread', category: 'Extras', price: 15.43, description: '', image: IMG.bread },
  { id: 127, name: 'Tuna', category: 'Extras', price: 130.43, description: '', image: IMG.fish },
  { id: 128, name: 'Cheese', category: 'Extras', price: 156.52, description: '', image: IMG.cheese },
  { id: 129, name: 'Egg', category: 'Extras', price: 30, description: '', image: IMG.egg },
  { id: 130, name: 'Milk', category: 'Extras', price: 60.86, description: '', image: IMG.latte },
  { id: 131, name: 'Butter', category: 'Extras', price: 60.86, description: '', image: IMG.cheese },
  { id: 132, name: 'Olive', category: 'Extras', price: 86.95, description: '', image: IMG.veg },
  { id: 133, name: 'Mushroom', category: 'Extras', price: 86.95, description: '', image: IMG.veg },
  { id: 134, name: 'Honey', category: 'Extras', price: 60.86, description: '', image: IMG.honey },
  { id: 135, name: 'Mayonnaise', category: 'Extras', price: 95.65, description: '', image: IMG.bread },
  { id: 136, name: 'Ketchup', category: 'Extras', price: 52.50, description: '', image: IMG.bread },
  { id: 137, name: 'Hot Sauce', category: 'Extras', price: 52.50, description: '', image: IMG.bread },
  { id: 138, name: 'Jam', category: 'Extras', price: 17.39, description: '', image: IMG.honey },
  { id: 139, name: 'Pancake Syrup', category: 'Extras', price: 34.78, description: '', image: IMG.honey },
  { id: 140, name: 'Extra Vegetable', category: 'Extras', price: 43.47, description: '', image: IMG.veg },

  // የሐበሻ ምግብ (Habesha Food)
  { id: 141, name: 'በየአይነቱ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 478, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 142, name: 'ሽሮ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 305, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 143, name: 'የፆም ፍርፍር', category: 'የሐበሻ ምግብ (Habesha Food)', price: 217.39, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 144, name: 'ቲማቲም ቁርጥ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 295.65, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 145, name: 'ሱፍ ፍትፍት', category: 'የሐበሻ ምግብ (Habesha Food)', price: 278.26, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 146, name: 'የዖም ኮንቦ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 404.34, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 147, name: 'ሽሮ በቲማቲም', category: 'የሐበሻ ምግብ (Habesha Food)', price: 321, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 148, name: 'የፆም ድርቆሽ ፍርፍር', category: 'የሐበሻ ምግብ (Habesha Food)', price: 260.86, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 149, name: 'የበግ ጥብስ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 695, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 150, name: 'ጭቅና ጥብስ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 521.17, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 151, name: 'ድለት', category: 'የሐበሻ ምግብ (Habesha Food)', price: 434, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 152, name: 'ቋንጣ ፍርፍር', category: 'የሐበሻ ምግብ (Habesha Food)', price: 391, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 153, name: 'ጥብስ ፍርፍር', category: 'የሐበሻ ምግብ (Habesha Food)', price: 391, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 154, name: 'ቦዘና ሽሮ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 347.82, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 155, name: 'ሽሮ በቅቤ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 330, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 156, name: 'ድርቆሸ ፍርፍር በቅቤ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 330, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 157, name: 'ድንች ወጥ በስጋ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 310.43, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 158, name: 'ምስር በስጋ', category: 'የሐበሻ ምግብ (Habesha Food)', price: 347.82, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },
  { id: 159, name: 'ድርቆሸ በቋንጣ ፍርፍር', category: 'የሐበሻ ምግብ (Habesha Food)', price: 365.21, description: 'የሐበሻ ምግብ', image: IMG.ethiopian },

  // Half & Half Platters
  { id: 160, name: 'ጥብስ በሽሮ', category: 'Half & Half Platters', price: 434.78, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 161, name: 'ቋንጣ ፍርፍር በሸሮ', category: 'Half & Half Platters', price: 382.60, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 162, name: 'ጥብስ ፍርፍር በሸሮ', category: 'Half & Half Platters', price: 426.08, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 163, name: 'ድርቆሽ በቋንጣ በበግ ጥብስ', category: 'Half & Half Platters', price: 391.30, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 164, name: 'ድርቆሽ በቋንጣ በጥብስ ፍርፍር', category: 'Half & Half Platters', price: 391.91, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 165, name: 'ድርቆሽ በቋንጣ በሽሮ', category: 'Half & Half Platters', price: 391.04, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 166, name: 'ድርቆሽ በቋንጣ በቦዘና ሽሮ', category: 'Half & Half Platters', price: 391.04, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 167, name: 'ድርቆሽ በቋንጣ በምስር በስጋ', category: 'Half & Half Platters', price: 382.60, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 168, name: 'ድርቆሽ በቋንጣ በድንች በስጋ', category: 'Half & Half Platters', price: 363.21, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 169, name: 'ድርቆሽ በቋንጣ በጭቅና ጥብስ', category: 'Half & Half Platters', price: 434.78, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 170, name: 'ጭቅና ጥብስ በምስር በስጋ', category: 'Half & Half Platters', price: 417.39, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
  { id: 171, name: 'ምስር በስጋ በሽሮ', category: 'Half & Half Platters', price: 347.82, description: 'ግማሽ ግማሽ', image: IMG.ethiopian },
];
