import { supabase } from '@/lib/supabase';

const IMAGES = {
  pizza: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop&auto=format',
  salad: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop&auto=format',
  pasta: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop&auto=format',
  fish: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&h=400&fit=crop&auto=format',
  breakfast: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a18066?w=600&h=400&fit=crop&auto=format',
  burger: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop&auto=format',
  habesha: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop&auto=format',
  cake: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=400&fit=crop&auto=format',
  drinks: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&h=400&fit=crop&auto=format',
};

const menuItems = [
  { name: 'Dolphin Special Pizza', description: '40x30cm - Our signature special pizza loaded with premium toppings', price: 28.99, category: 'Pizza', image: IMAGES.pizza, available: true, rating: 4.9 },
  { name: 'Special Pizza', description: 'Delicious special pizza with fresh ingredients', price: 24.99, category: 'Pizza', image: IMAGES.pizza, available: true, rating: 4.7 },
  { name: 'Vegetable with Tuna Pizza', description: 'Pizza topped with fresh vegetables and tuna', price: 22.99, category: 'Pizza', image: IMAGES.pizza, available: true, rating: 4.5 },
  { name: 'Margarita Pizza', description: 'Classic margarita pizza with mozzarella and basil', price: 18.99, category: 'Pizza', image: IMAGES.pizza, available: true, rating: 4.6 },
  { name: 'Meat Lover Pizza', description: 'Loaded with assorted meats for the meat enthusiast', price: 26.99, category: 'Pizza', image: IMAGES.pizza, available: true, rating: 4.8 },
  { name: 'Chicken Pizza', description: 'Tender chicken pieces with savory toppings', price: 22.99, category: 'Pizza', image: IMAGES.pizza, available: true, rating: 4.5 },
  { name: 'Vegetable Pizza', description: 'Fresh garden vegetables on a crispy crust', price: 18.99, category: 'Pizza', image: IMAGES.pizza, available: true, rating: 4.3 },
  { name: 'Tuna Pizza', description: 'Premium tuna with melted cheese and herbs', price: 22.99, category: 'Pizza', image: IMAGES.pizza, available: true, rating: 4.4 },
  { name: 'Altono Pizza', description: 'Special Altono pizza with unique seasoning blend', price: 24.99, category: 'Pizza', image: IMAGES.pizza, available: true, rating: 4.6 },
  { name: 'Dolphin Special Salad', description: 'Our signature salad with premium fresh ingredients', price: 12.99, category: 'Salad', image: IMAGES.salad, available: true, rating: 4.8 },
  { name: 'Mixed Salad', description: 'Fresh mixed garden salad with dressing', price: 9.99, category: 'Salad', image: IMAGES.salad, available: true, rating: 4.4 },
  { name: 'Tuna Salad (Special)', description: 'Special tuna salad with fresh vegetables', price: 13.99, category: 'Salad', image: IMAGES.salad, available: true, rating: 4.6 },
  { name: 'Chicken Salad', description: 'Grilled chicken breast on a bed of fresh greens', price: 14.99, category: 'Salad', image: IMAGES.salad, available: true, rating: 4.5 },
  { name: 'Tomato Sauce Pasta', description: 'Classic pasta with rich tomato sauce', price: 14.99, category: 'Pasta & Rice', image: IMAGES.pasta, available: true, rating: 4.3 },
  { name: 'Bolognaise Sauce Pasta', description: 'Pasta with hearty bolognaise meat sauce', price: 16.99, category: 'Pasta & Rice', image: IMAGES.pasta, available: true, rating: 4.6 },
  { name: 'Vegetable Pasta', description: 'Pasta with fresh seasonal vegetables', price: 14.99, category: 'Pasta & Rice', image: IMAGES.pasta, available: true, rating: 4.4 },
  { name: 'Tuna Sauce Pasta', description: 'Pasta with creamy tuna sauce', price: 16.99, category: 'Pasta & Rice', image: IMAGES.pasta, available: true, rating: 4.5 },
  { name: 'Vegetable with Tuna Pasta', description: 'Pasta with vegetables and tuna', price: 17.99, category: 'Pasta & Rice', image: IMAGES.pasta, available: true, rating: 4.5 },
  { name: 'Rice with Vegetable', description: 'Steamed rice with mixed vegetables', price: 12.99, category: 'Pasta & Rice', image: IMAGES.pasta, available: true, rating: 4.2 },
  { name: 'Lasagna', description: 'Classic lasagna with layers of pasta, meat sauce and cheese', price: 18.99, category: 'Pasta & Rice', image: IMAGES.pasta, available: true, rating: 4.7 },
  { name: 'Fish Cutlet', description: 'Crispy golden fish cutlet with dipping sauce', price: 15.99, category: 'Fish', image: IMAGES.fish, available: true, rating: 4.5 },
  { name: 'Grilled Fish', description: 'Fresh fish grilled to perfection with herbs', price: 18.99, category: 'Fish', image: IMAGES.fish, available: true, rating: 4.7 },
  { name: 'Fish Goulash', description: 'Hearty fish goulash with rich sauce', price: 16.99, category: 'Fish', image: IMAGES.fish, available: true, rating: 4.4 },
  { name: 'Fish Package', description: 'Special fish package with seasonal sides', price: 19.99, category: 'Fish', image: IMAGES.fish, available: true, rating: 4.6 },
  { name: 'Stir Fried Fish', description: 'Wok-tossed fish with vegetables in savory sauce', price: 17.99, category: 'Fish', image: IMAGES.fish, available: true, rating: 4.5 },
  { name: 'Dolphin Special Ful', description: 'Our signature ful medames dish - a hearty breakfast classic', price: 8.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.7 },
  { name: 'Special Ful', description: 'Special ful medames with fresh toppings', price: 7.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.5 },
  { name: 'Normal Ful', description: 'Classic ful medames', price: 5.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.3 },
  { name: 'Yogurt', description: 'Fresh creamy yogurt', price: 4.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.2 },
  { name: 'Tuna Sils', description: 'Tuna sils - a savory breakfast dish', price: 8.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.4 },
  { name: 'Egg with Tomato Sauce', description: 'Fried eggs in rich tomato sauce', price: 6.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.3 },
  { name: 'Omelette with Cheese', description: 'Fluffy omelette filled with melted cheese', price: 7.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.5 },
  { name: 'Fried Egg', description: 'Classic fried egg your way', price: 4.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.1 },
  { name: 'Plain Omelette', description: 'Simple fluffy plain omelette', price: 5.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.2 },
  { name: 'Tomato Sils', description: 'Tomato sils - a flavorful breakfast dish', price: 6.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.3 },
  { name: 'Scrambled Egg', description: 'Light and fluffy scrambled eggs', price: 5.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.2 },
  { name: 'Fetira with Honey', description: 'Traditional fetira drizzled with honey', price: 7.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.6 },
  { name: 'Fetira with Egg', description: 'Fetira served with egg', price: 7.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.4 },
  { name: 'Special Omelette', description: 'Special omelette with premium fillings', price: 8.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.6 },
  { name: 'Chechebsa', description: 'Traditional Ethiopian chechebsa', price: 7.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.5 },
  { name: 'Special Chechebsa', description: 'Special chechebsa with extra toppings', price: 9.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.7 },
  { name: 'Teff Chechebsa with Honey', description: 'Teff-based chechebsa with honey', price: 9.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.6 },
  { name: 'Teff Chechebsa with Egg', description: 'Teff chechebsa served with egg', price: 9.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.5 },
  { name: 'Special Teff Chechebsa', description: 'Special teff chechebsa with premium toppings', price: 11.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.7 },
  { name: 'Teff Chechebsa Plain', description: 'Plain teff chechebsa', price: 7.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.3 },
  { name: 'Special Fetira', description: 'Special fetira with assorted toppings', price: 9.99, category: 'Breakfast & Light Meals', image: IMAGES.breakfast, available: true, rating: 4.6 },
  { name: 'Dolphin Special Double Beef Burger', description: 'Our signature double beef burger with premium toppings', price: 18.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.9 },
  { name: 'Dolphin Special Burger', description: 'Special dolphin burger with our secret sauce', price: 15.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.7 },
  { name: 'Beef Burger', description: 'Classic beef burger with fresh lettuce and tomato', price: 12.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.5 },
  { name: 'Chicken Burger', description: 'Grilled chicken burger with crispy coating', price: 13.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.5 },
  { name: 'Cheese Burger', description: 'Beef burger with melted cheese', price: 13.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.4 },
  { name: 'Fish Burger', description: 'Crispy fish fillet burger with tartar sauce', price: 14.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.3 },
  { name: 'Tuna Sandwich', description: 'Fresh tuna sandwich with vegetables', price: 11.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.4 },
  { name: 'Club Sandwich', description: 'Classic club sandwich with layers of meat and cheese', price: 12.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.5 },
  { name: 'Vegetable Burger', description: 'Hearty vegetable patty burger', price: 11.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.2 },
  { name: 'Beef Combo', description: 'Beef combo with fries and drink', price: 16.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.6 },
  { name: 'Egg Burger', description: 'Burger topped with a fried egg', price: 13.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.3 },
  { name: 'French Fries', description: 'Crispy golden french fries', price: 5.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.4 },
  { name: 'Chicken Combo', description: 'Chicken combo with fries and drink', price: 16.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.6 },
  { name: 'Grilled Beef Fillet Steak', description: 'Premium grilled beef fillet steak with sides', price: 24.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.8 },
  { name: 'Roasted Chicken Breast', description: 'Herb-roasted chicken breast with vegetables', price: 18.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.6 },
  { name: 'Grilled Tilapia Fish', description: 'Fresh tilapia grilled to perfection', price: 17.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.5 },
  { name: 'Chicken Sandwich', description: 'Grilled chicken sandwich with fresh toppings', price: 12.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.4 },
  { name: 'Tuna Club Sandwich', description: 'Tuna club sandwich with extra fillings', price: 13.99, category: 'Burger & Sandwich', image: IMAGES.burger, available: true, rating: 4.4 },
  { name: 'የፆም ፍርፍር (Fasting Firfir)', description: 'የፆም ምግብ - Traditional fasting firfir, a classic Ethiopian fasting dish', price: 8.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.6 },
  { name: 'ቲማቲም ቁርጥ (Tomato Kurt)', description: 'የፆም ምግብ - Fresh tomato kurt salad with traditional seasonings', price: 6.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.4 },
  { name: 'የፆም ኮምቦ (Fasting Combo)', description: 'የፆም ምግብ - Fasting combo platter with assorted items', price: 12.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.7 },
  { name: 'ሽሮ በቲማቲም (Shiro with Tomato)', description: 'የፆም ምግብ - Shiro stew prepared with fresh tomatoes', price: 8.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.5 },
  { name: 'የፆም ድርቆሽ ፍርፍር (Fasting Dirkosh Firfir)', description: 'የፆም ምግብ - Fasting dirkosh firfir, a flavorful fasting meal', price: 9.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.5 },
  { name: 'የበግ ጥብስ (Lamb Tibs)', description: 'ምሳ/እራት - Sautéed lamb tibs with aromatic spices and onions', price: 16.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.8 },
  { name: 'ድለት (Dulet)', description: 'ምሳ/እራት - Traditional Ethiopian dulet - minced meat with spices', price: 14.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.7 },
  { name: 'ቋንጣ ፍርፍር (Kanta Firfir)', description: 'ምሳ/እራት - Kanta firfir, a spicy traditional dish', price: 13.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.6 },
  { name: 'ጥብስ ፍርፍር (Tibs Firfir)', description: 'ምሳ/እራት - Tibs firfir, sautéed meat with injera pieces', price: 14.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.6 },
  { name: 'ቦዘና ሽሮ (Bozena Shiro)', description: 'ምሳ/እራት - Bozena shiro, rich and flavorful shiro stew', price: 12.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.5 },
  { name: 'ሽሮ በቅቤ (Shiro with Butter)', description: 'ምሳ/እራት - Shiro prepared with clarified butter for rich flavor', price: 10.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.5 },
  { name: 'ድርቆሽ ፍርፍር በቅቤ (Dirkosh Firfir with Butter)', description: 'ምሳ/እራት - Dirkosh firfir with butter', price: 11.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.4 },
  { name: 'ድንች ወጥ በስጋ (Potato Stew with Meat)', description: 'ምሳ/እራት - Hearty potato stew with tender meat pieces', price: 13.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.5 },
  { name: 'ምስር በስጋ (Lentils with Meat)', description: 'ምሳ/እራት - Lentil stew with meat, a nutritious and delicious meal', price: 13.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.5 },
  { name: 'ጥብስ በሽሮ (Tibs with Shiro)', description: 'ግማሽ ግማሽ - Half tibs and half shiro platter', price: 15.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.7 },
  { name: 'ቋንጣ ፍርፍር በሸሮ (Kanta Firfir with Shiro)', description: 'ግማሽ ግማሽ - Half kanta firfir and half shiro platter', price: 14.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.6 },
  { name: 'ጥብስ ፍርፍር በሸሮ (Tibs Firfir with Shiro)', description: 'ግማሽ ግማሽ - Half tibs firfir and half shiro platter', price: 14.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.6 },
  { name: 'ድርቆሽ በቋንጣ በበግ ጥብስ (Dirkosh & Kanta with Lamb Tibs)', description: 'ግማሽ ግማሽ - Half dirkosh & kanta with lamb tibs platter', price: 17.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.8 },
  { name: 'ድርቆሽ በቋንጣ በጥብስ ፍርፍር (Dirkosh & Kanta with Tibs Firfir)', description: 'ግማሽ ግማሽ - Half dirkosh & kanta with tibs firfir platter', price: 16.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.7 },
  { name: 'ድርቆሽ በቋንጣ በሽሮ (Dirkosh & Kanta with Shiro)', description: 'ግማሽ ግማሽ - Half dirkosh & kanta with shiro platter', price: 14.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.5 },
  { name: 'ድርቆሽ በቋንጣ በቦዘና ሽሮ (Dirkosh & Kanta with Bozena Shiro)', description: 'ግማሽ ግማሽ - Half dirkosh & kanta with bozena shiro platter', price: 15.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.6 },
  { name: 'ድርቆሽ በቋንጣ በምስር በስጋ (Dirkosh & Kanta with Lentils with Meat)', description: 'ግማሽ ግማሽ - Half dirkosh & kanta with lentils and meat platter', price: 15.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.6 },
  { name: 'ድርቆሽ በቋንጣ በድንች በስጋ (Dirkosh & Kanta with Potato with Meat)', description: 'ግማሽ ግማሽ - Half dirkosh & kanta with potato and meat platter', price: 15.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.5 },
  { name: 'ድርቆሽ በቋንጣ በጭቅና ጥብስ (Dirkosh & Kanta with Chikina Tibs)', description: 'ግማሽ ግማሽ - Half dirkosh & kanta with chikina tibs platter', price: 16.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.7 },
  { name: 'ጭቅና ጥብስ በምስር በስጋ (Chikina Tibs with Lentils with Meat)', description: 'ግማሽ ግማሽ - Half chikina tibs with lentils and meat platter', price: 16.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.6 },
  { name: 'ምስር በስጋ በሽሮ (Lentils with Meat and Shiro)', description: 'ግማሽ ግማሽ - Half lentils with meat and shiro platter', price: 14.99, category: 'Habesha Food', image: IMAGES.habesha, available: true, rating: 4.5 },
  { name: 'Tiramisu with Cup', description: 'Classic Italian tiramisu served in a cup', price: 8.99, category: 'Cake & Snacks', image: IMAGES.cake, available: true, rating: 4.8 },
  { name: 'Chocolate Cake', description: 'Rich and decadent chocolate cake', price: 7.99, category: 'Cake & Snacks', image: IMAGES.cake, available: true, rating: 4.7 },
  { name: 'White Forest Torta', description: 'Delicate white forest torta', price: 8.99, category: 'Cake & Snacks', image: IMAGES.cake, available: true, rating: 4.6 },
  { name: 'Black Forest Torta', description: 'Classic black forest torta with cherries', price: 8.99, category: 'Cake & Snacks', image: IMAGES.cake, available: true, rating: 4.7 },
  { name: 'Tiramisu Torta', description: 'Tiramisu torta - a twist on the classic', price: 9.99, category: 'Cake & Snacks', image: IMAGES.cake, available: true, rating: 4.6 },
  { name: 'Banana Cake', description: 'Moist banana cake with cream', price: 7.99, category: 'Cake & Snacks', image: IMAGES.cake, available: true, rating: 4.5 },
  { name: 'Marble Cake', description: 'Beautiful marble cake with vanilla and chocolate swirls', price: 7.99, category: 'Cake & Snacks', image: IMAGES.cake, available: true, rating: 4.4 },
  { name: 'Caramel Fasting', description: 'Caramel fasting - a delicious fasting-friendly dessert', price: 7.99, category: 'Cake & Snacks', image: IMAGES.cake, available: true, rating: 4.5 },
  { name: 'Sambusa Meat', description: 'Crispy sambusa filled with seasoned meat', price: 5.99, category: 'Cake & Snacks', image: IMAGES.cake, available: true, rating: 4.6 },
  { name: 'Sambusa Lentil', description: 'Crispy sambusa filled with spiced lentils', price: 5.99, category: 'Cake & Snacks', image: IMAGES.cake, available: true, rating: 4.4 },
  { name: 'Bread', description: 'Freshly baked bread', price: 2.99, category: 'Extras', image: IMAGES.breakfast, available: true, rating: 4.2 },
  { name: 'Tuna', description: 'Extra serving of tuna', price: 4.99, category: 'Extras', image: IMAGES.breakfast, available: true, rating: 4.1 },
  { name: 'Cheese', description: 'Extra cheese portion', price: 3.99, category: 'Extras', image: IMAGES.breakfast, available: true, rating: 4.3 },
  { name: 'Egg', description: 'Extra egg', price: 2.49, category: 'Extras', image: IMAGES.breakfast, available: true, rating: 4.0 },
  { name: 'Milk', description: 'Fresh milk', price: 2.99, category: 'Extras', image: IMAGES.breakfast, available: true, rating: 4.1 },
  { name: 'Butter', description: 'Creamy butter portion', price: 2.49, category: 'Extras', image: IMAGES.breakfast, available: true, rating: 4.2 },
  { name: 'Olive', description: 'Extra serving of olives', price: 3.49, category: 'Extras', image: IMAGES.salad, available: true, rating: 4.0 },
  { name: 'Mushroom', description: 'Fresh sautéed mushrooms', price: 3.99, category: 'Extras', image: IMAGES.salad, available: true, rating: 4.3 },
  { name: 'Honey', description: 'Pure natural honey', price: 2.99, category: 'Extras', image: IMAGES.breakfast, available: true, rating: 4.2 },
  { name: 'Mayonnaise', description: 'Extra mayonnaise', price: 1.49, category: 'Extras', image: IMAGES.salad, available: true, rating: 3.9 },
  { name: 'Ketchup', description: 'Extra ketchup', price: 1.49, category: 'Extras', image: IMAGES.burger, available: true, rating: 3.9 },
  { name: 'Hot Sauce', description: 'Spicy hot sauce', price: 1.49, category: 'Extras', image: IMAGES.habesha, available: true, rating: 4.1 },
  { name: 'Jam', description: 'Assorted fruit jam', price: 2.49, category: 'Extras', image: IMAGES.breakfast, available: true, rating: 4.0 },
  { name: 'Pancake Syrup', description: 'Sweet pancake syrup', price: 2.99, category: 'Extras', image: IMAGES.breakfast, available: true, rating: 4.1 },
  { name: 'Extra Vegetable', description: 'Extra serving of fresh vegetables', price: 3.99, category: 'Extras', image: IMAGES.salad, available: true, rating: 4.0 },
  { name: '1/7 Liter Water', description: 'Pure bottled water - small size', price: 1.49, category: 'Soft Drinks', image: IMAGES.drinks, available: true, rating: 4.0 },
  { name: '1/4 Liter Water', description: 'Pure bottled water - medium size', price: 1.99, category: 'Soft Drinks', image: IMAGES.drinks, available: true, rating: 4.0 },
  { name: '1 Liter Water', description: 'Pure bottled water - large size', price: 2.99, category: 'Soft Drinks', image: IMAGES.drinks, available: true, rating: 4.0 },
  { name: 'Soft Drinks', description: 'Assorted soft drinks (Coca-Cola, Sprite, Fanta)', price: 2.49, category: 'Soft Drinks', image: IMAGES.drinks, available: true, rating: 4.2 },
  { name: 'Ambo', description: 'Ethiopian Ambo mineral water', price: 2.99, category: 'Soft Drinks', image: IMAGES.drinks, available: true, rating: 4.1 },
  { name: 'Malta Guinness', description: 'Malta Guinness non-alcoholic malt drink', price: 3.49, category: 'Soft Drinks', image: IMAGES.drinks, available: true, rating: 4.3 },
  { name: 'Sofi Malt', description: 'Sofi malt non-alcoholic beverage', price: 3.49, category: 'Soft Drinks', image: IMAGES.drinks, available: true, rating: 4.2 },
  { name: 'Coke 500ml', description: 'Coca-Cola 500ml bottle', price: 3.49, category: 'Soft Drinks', image: IMAGES.drinks, available: true, rating: 4.1 },
  { name: 'Red Bull', description: 'Red Bull energy drink', price: 4.99, category: 'Soft Drinks', image: IMAGES.drinks, available: true, rating: 4.0 },
  { name: 'Novida', description: 'Novida refreshing beverage', price: 3.49, category: 'Soft Drinks', image: IMAGES.drinks, available: true, rating: 4.1 },
  { name: 'Rift Valley', description: 'Rift Valley wine', price: 12.99, category: 'Alcoholic Beverages', image: IMAGES.drinks, available: true, rating: 4.3 },
  { name: 'Chardonnay', description: 'Premium Chardonnay wine', price: 14.99, category: 'Alcoholic Beverages', image: IMAGES.drinks, available: true, rating: 4.5 },
  { name: 'Acacia', description: 'Acacia wine', price: 12.99, category: 'Alcoholic Beverages', image: IMAGES.drinks, available: true, rating: 4.2 },
  { name: 'Cavee', description: 'Cavee wine', price: 11.99, category: 'Alcoholic Beverages', image: IMAGES.drinks, available: true, rating: 4.1 },
  { name: 'Axumit', description: 'Axumit wine', price: 12.99, category: 'Alcoholic Beverages', image: IMAGES.drinks, available: true, rating: 4.3 },
  { name: 'Kemila', description: 'Kemila wine', price: 11.99, category: 'Alcoholic Beverages', image: IMAGES.drinks, available: true, rating: 4.2 },
  { name: 'Beer', description: 'Assorted beers - cold and refreshing', price: 4.99, category: 'Alcoholic Beverages', image: IMAGES.drinks, available: true, rating: 4.4 },
  { name: 'Gebeta', description: 'Gebeta beer', price: 4.99, category: 'Alcoholic Beverages', image: IMAGES.drinks, available: true, rating: 4.3 },
  { name: 'Dolphin Special Juice', description: 'Our signature fresh juice blend', price: 6.99, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.8 },
  { name: 'Banana Shake', description: 'Creamy banana milkshake', price: 5.99, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.6 },
  { name: 'Mixed Juice', description: 'Fresh mixed fruit juice', price: 5.99, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.5 },
  { name: 'Papaya Juice', description: 'Fresh papaya juice', price: 5.49, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.4 },
  { name: 'Pineapple Juice', description: 'Fresh pineapple juice', price: 5.49, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.5 },
  { name: 'Avocado Juice', description: 'Creamy avocado juice', price: 5.99, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.6 },
  { name: 'Strawberry Juice', description: 'Fresh strawberry juice', price: 5.99, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.5 },
  { name: 'Mango Juice', description: 'Fresh mango juice', price: 5.99, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.6 },
  { name: 'Strawberry with Milk', description: 'Strawberry milkshake', price: 6.49, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.5 },
  { name: 'Fruit Cocktail', description: 'Assorted fruit cocktail juice', price: 6.99, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.4 },
  { name: 'Strawberry Mix', description: 'Strawberry mixed juice blend', price: 6.49, category: 'Juice & Shakes', image: IMAGES.drinks, available: true, rating: 4.5 },
  { name: 'Macchiato / Fasting Macchiato', description: 'Italian-style macchiato or fasting macchiato', price: 4.49, category: 'Hot Drinks', image: IMAGES.drinks, available: true, rating: 4.6 },
  { name: 'Coffee / Traditional Coffee / American Coffee', description: 'Fresh brewed coffee - regular, traditional Ethiopian, or American', price: 3.99, category: 'Hot Drinks', image: IMAGES.drinks, available: true, rating: 4.7 },
  { name: 'Espresso', description: 'Rich and bold espresso shot', price: 3.49, category: 'Hot Drinks', image: IMAGES.drinks, available: true, rating: 4.5 },
  { name: 'Milk with Coffee', description: 'Coffee with steamed milk', price: 4.49, category: 'Hot Drinks', image: IMAGES.drinks, available: true, rating: 4.4 },
  { name: 'Cappuccino', description: 'Classic Italian cappuccino', price: 4.99, category: 'Hot Drinks', image: IMAGES.drinks, available: true, rating: 4.6 },
  { name: 'Café Latte', description: 'Smooth café latte', price: 4.99, category: 'Hot Drinks', image: IMAGES.drinks, available: true, rating: 4.5 },
  { name: 'Tea (Special/Lepton/Green/Ginger/Peanut/Lemon)', description: 'Assorted teas - special, lepton, green, ginger, peanut, or lemon', price: 3.49, category: 'Hot Drinks', image: IMAGES.drinks, available: true, rating: 4.3 },
  { name: 'Hot Milk', description: 'Warm steamed milk', price: 3.49, category: 'Hot Drinks', image: IMAGES.drinks, available: true, rating: 4.1 },
  { name: 'Hot Chocolate', description: 'Rich hot chocolate drink', price: 4.99, category: 'Hot Drinks', image: IMAGES.drinks, available: true, rating: 4.5 },
];

export async function GET() {
  try {
    const { data: existing } = await supabase.from('menu_items').select('id').limit(1);

    if (existing && existing.length > 0) {
      const { error: deleteError } = await supabase.from('menu_items').delete().neq('id', 0);
      if (deleteError) throw deleteError;
    }

    const { data, error } = await supabase.from('menu_items').insert(menuItems).select();
    if (error) throw error;

    return Response.json({
      success: true,
      message: `Seeded ${data.length} menu items successfully`,
      count: data.length,
    });
  } catch (error: any) {
    return Response.json({ success: false, error: error.message }, { status: 500 });
  }
}
